### ISSUE TITLE
provider FAILED undefined

### ISSUE THREAD

**Issue by garthk** [launchdarkly/ld-vscode#16] opened 2019-09-19 04:26 UTC
`ld-vscode` causes the extension host to log this every few seconds:
> ```
> [2019-09-19 14:07:56.848] [exthost] [error] [launchdarkly.launchdarkly] provider FAILED
> [2019-09-19 14:07:56.848] [exthost] [error] undefined
> ```
It does so even if I've put the SDK key and API token in my settings and the extension is happily popping up summaries for flags and suggesting their keys when I start typing strings.

**Comment by atrakh** [comment] 2019-12-27 02:28
Hi @garthk,

Thanks for reporting this. I haven't been able to reproduce this issue on my end. We did just release a new version of the extension which resolved a few different logging issues. Can you try updating and let me know if this reoccurs?

**Comment by atrakh** [comment] 2020-01-06 18:41
Given we haven't been able to reproduce, and have made some improvements to error handling and logging since this issue was created, I'm going to close this issue for now.

If this reoccurs, please comment here again and let us know.

**Closed by atrakh** 2020-01-06 18:41 UTC
